### ISSUE TITLE
Problem when executing ./cron.php --run=controller/cronfunction

### ISSUE THREAD

**Issue by SalvadorP** [compwright/codeigniter-cli-bootstrap#1]
Hello, I'm using your codeigniter-cli-bootstrap solution for running a cron in my CI project.

I have  a problem, when I run the script from outside the document root, it runs, but gives me this error:

**An Error Was Encountered
The URI you submitted has disallowed characters.**

I checked the configuration vars for the index.php and it's ok.
The server name var it's ok too.

The installation has this format:

myserver.com/app1/controller/cronfunction
myserver.com/app2/controller/cronfunction

I tried to access myserver.com/app2/controller/cronfunction but gives me the error.

I don't know if it's a problem with my installation, a CI problem or something else.

Thanks.

Edit. I want to tag this like a question but I don't know how.

Check cron.php line 67 it needs a ';'

**Comment by compwright** [comment]
The semicolon is fixed, commit fac8e330

**Comment by SalvadorP** [comment]
It doesn't receive the "--run=controller/function" right 
When it calls the controller using the correct route it passes the direction like "--run=controller" not "controller/function", can you check that?

I don't know if it's my configuration or this script but I think I'll use other solution for the cron jobs.

Thanks.

**Comment by isocano** [comment]
I have the same problem as SalvadorP.

"An Error Was Encountered
The URI you submitted has disallowed characters."

**Comment by pablovezgz** [comment]
Fixed: 

https://github.com/pvm23/codeigniter-cli-bootstrap

**Comment by compwright** [comment]
Thank you @pvm23!
