### ISSUE TITLE
Strange errors

### ISSUE THREAD

**Issue by brizoo** [compwright/codeigniter-cli-bootstrap#3]
Hi,

First of all, I would like to thank you for this job. I'm happy that it will help me a lot.

I'm encountering a strange error though. When I launch the cron.php file which I've downloaded from here, I have a lot of errors in putty.

![PuTTY](https://f.cloud.github.com/assets/1492472/65088/3c8c01e4-5e69-11e2-8088-c2b48f0b41a7.jpg)

At the end, I have the content of the home page. This is strange, I have it even in my log file which I've specified before.

Here is my command line to launch it:
 ./cron.php --run=/crons/export_conciergerie --show-output 

What do you think this can be ?

Thanks

**Comment by compwright** [comment]
The only error that has to do with the cron.php file is the notice error, and that has been fixed in the latest version. The other errors are from something else. Glad you found this useful!
