### ISSUE TITLE
unexpected '/'

### ISSUE THREAD

**Issue by dhamaso** [compwright/codeigniter-cli-bootstrap#4]
/usr/local/bin/php -q -f /home/site/public_html/cron.php --run=/cron/confirm_status

So what's wrong?, can you help me?

cron.php
define('CRON_CI_INDEX', '/home/site/public_html/index.php');
define('CRON_LOG', 'cron.log');

**Comment by compwright** [comment]
Can you please provide more information about the error, such as the offending file and line number?

**Comment by compwright** [comment]
Closing for now, feel free to re-open if you have additional information to add.
